# SELECT ID, 
# IF((RANK() OVER (ORDER BY SIZE_OF_COLONY DESC)) / (SELECT SUM(*) FROM ECOLI_DATA) <= 0.25, 'CRITICAL', 'MEDIUM')) AS COLONY_NAME
# FROM ECOLI_DATA

SELECT ID,
CASE WHEN RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) / (SELECT COUNT(*) FROM ECOLI_DATA) <= 0.25 THEN 'CRITICAL'
WHEN RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) / (SELECT COUNT(*) FROM ECOLI_DATA) <= 0.5 THEN 'HIGH'
WHEN RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) / (SELECT COUNT(*) FROM ECOLI_DATA) <= 0.75 THEN 'MEDIUM'
ELSE 'LOW'
END COLONY_NAME
FROM ECOLI_DATA
ORDER BY ID