# SELECT ID, 
# IF((RANK() OVER (ORDER BY SIZE_OF_COLONY DESC)) / (SELECT SUM(*) FROM ECOLI_DATA) <= 0.25, 'CRITICAL', 'MEDIUM')) AS COLONY_NAME
# FROM ECOLI_DATA

SELECT ID,
CASE WHEN PERCENTAGE <= 0.25 THEN 'CRITICAL'
WHEN PERCENTAGE <= 0.5 THEN 'HIGH'
WHEN PERCENTAGE <= 0.75 THEN 'MEDIUM'
ELSE 'LOW' END COLONY_NAME
FROM (
    SELECT ID, RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) / (SELECT COUNT(*) PERCENTAGE FROM ECOLI_DATA) PERCENTAGE
    FROM ECOLI_DATA
) AS E
ORDER BY ID