SELECT REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
FROM (
    SELECT R.REST_ID, R.REST_NAME, R.FOOD_TYPE, R.FAVORITES, R.ADDRESS, RR.REVIEW_SCORE
    FROM REST_INFO R
    JOIN REST_REVIEW RR ON R.REST_ID = RR.REST_ID
)
AS REST_SEOUL

WHERE ADDRESS LIKE '서울%'

GROUP BY REST_ID

ORDER BY SCORE DESC, FAVORITES DESC