SELECT REST_SEOUL.REST_ID, REST_SEOUL.REST_NAME, REST_SEOUL.FOOD_TYPE, REST_SEOUL.FAVORITES, REST_SEOUL.ADDRESS, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE

FROM(
    SELECT REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS
    FROM REST_INFO
    WHERE ADDRESS LIKE '서울%'
) AS REST_SEOUL 

JOIN REST_REVIEW AS REVIEW
ON REST_SEOUL.REST_ID = REVIEW.REST_ID

GROUP BY REST_SEOUL.REST_ID
ORDER BY SCORE DESC, REST_SEOUL.FAVORITES DESC