SELECT X.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE X
JOIN REST_REVIEW R ON X.MEMBER_ID = R.MEMBER_ID
WHERE X.MEMBER_ID =
(
    SELECT M.MEMBER_ID
    FROM MEMBER_PROFILE M
    JOIN REST_REVIEW R ON M.MEMBER_ID = R.MEMBER_ID
    GROUP BY M.MEMBER_ID
    ORDER BY COUNT(*) DESC
    LIMIT 1
)
ORDER BY REVIEW_DATE, R.REVIEW_TEXT