-- 생산일자가 2022년 5월인 식품들의 식품 ID, 식품 이름, 총매출
# SELECT P.PRODUCT_ID, P.PRODUCT_NAME, SUM(O.AMOUNT)*P.PRICE AS TOTAL_SALES
# FROM FOOD_PRODUCT P
# JOIN FOOD_ORDER O ON P.PRODUCT_ID = O.PRODUCT_ID AND O.PRODUCE_DATE >= '2022-05-01' AND O.PRODUCE_DATE <= '2022.05-30'
# GROUP BY P.PRODUCT_ID
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, SUM(O.AMOUNT)*P.PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT P
JOIN FOOD_ORDER O ON P.PRODUCT_ID = O.PRODUCT_ID AND O.PRODUCE_DATE >= '2022-05-01' AND O.PRODUCE_DATE <= '2022-05-31'
GROUP BY P.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, O.PRODUCT_ID