# SELECT FLAVOR, TOTAL_ORDER
# FROM (
#     SELECT F.SHIPMENT_ID, F.FLAVOR, SUM(F.TOTAL_ORDER) + SUM(J.TOTAL_ORDER) AS TOTAL_ORDER
#     FROM FIRST_HALF F
#     GROUP BY F.FLAVOR
#     JOIN JULY J ON F.SHIPMENT_ID = J.SHIPMENT_ID
#     GROUP BY J.FLAVOR
# ) AS R
# ORDER BY TOTAL_ORDER DESC
# LIMIT 3

SELECT FH.FLAVOR
FROM (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM FIRST_HALF
    GROUP BY FLAVOR
) AS FH
JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
) AS J
ON FH.FLAVOR = J.FLAVOR
ORDER BY FH.TOTAL_ORDER + J.TOTAL_ORDER DESC
LIMIT 3