WITH X AS (
    SELECT S.*
    FROM USER_INFO U
    JOIN ONLINE_SALE S ON U.USER_ID = S.USER_ID
    WHERE YEAR(U.JOINED) = 2021
)

SELECT YEAR(SALES_DATE) AS YEAR,
MONTH(SALES_DATE) AS MONTH,
COUNT(DISTINCT USER_ID) AS PURCHASED_USERS,
ROUND(COUNT(DISTINCT USER_ID) / (SELECT COUNT(DISTINCT(USER_ID)) FROM USER_INFO WHERE YEAR(JOINED) = 2021), 1) AS PURCHASED_RATIO
FROM X
GROUP BY (DATE_FORMAT(SALES_DATE, '%Y%m'))
ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE)