WITH M AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MC
    FROM ECOLI_DATA
    GROUP BY YEAR
)

SELECT 
    YEAR(E.DIFFERENTIATION_DATE) AS YEAR, 
    (M.MC - E.SIZE_OF_COLONY) AS YEAR_DEV, 
    E.ID
FROM ECOLI_DATA E
JOIN M ON YEAR(E.DIFFERENTIATION_DATE) = M.YEAR
ORDER BY YEAR, YEAR_DEV